[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 100000
via_ir = false
auto_detect_remappings = false

[profile.default.fuzz]
runs = 256

# Remappings  
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@uniswap/v4-core/=lib/v4-core/src/",
    "@openzeppelin/contracts/=lib/v4-core/lib/openzeppelin-contracts/contracts/"
]
